services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:

# services:
#   postgres:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=postgrespw
#     ports:
#       - 5432:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
